name: Demo Pipeline
on: workflow_dispatch

env:
    RepoName: abc
    version: 1

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Clone Repo
              run: |
                  echo "Clonning the repo ${{env.RepoName}}"
            - name: Version
              run: echo "${{env.version}}"
